/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTaskRequest { 
    title: string;
    description?: string;
    priority?: CreateTaskRequest.PriorityEnum;
    assigneeId?: string;
    dueDate?: string;
}
export namespace CreateTaskRequest {
    export const PriorityEnum = {
        Low: 'LOW',
        Medium: 'MEDIUM',
        High: 'HIGH',
        Critical: 'CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


