/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface PageResponseUserDto { 
    content?: Array<UserDto>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    last?: boolean;
}

