/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectDashboardDto { 
    projectId?: string;
    projectName?: string;
    totalTasks?: number;
    tasksByStatus?: { [key: string]: number; };
    tasksByAssignee?: { [key: string]: number; };
    tasksByAssigneeName?: { [key: string]: number; };
    completionPercentage?: number;
}

