/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface ProjectDto { 
    id?: string;
    name?: string;
    description?: string;
    status?: ProjectDto.StatusEnum;
    owner?: UserDto;
    members?: Set<UserDto>;
    taskCount?: number;
    createdAt?: string;
    updatedAt?: string;
}
export namespace ProjectDto {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Archived: 'ARCHIVED',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


