/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface TaskDto { 
    id?: string;
    title?: string;
    description?: string;
    status?: TaskDto.StatusEnum;
    priority?: TaskDto.PriorityEnum;
    projectId?: string;
    projectName?: string;
    assignee?: UserDto;
    reporter?: UserDto;
    dueDate?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace TaskDto {
    export const StatusEnum = {
        Todo: 'TODO',
        InProgress: 'IN_PROGRESS',
        Done: 'DONE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PriorityEnum = {
        Low: 'LOW',
        Medium: 'MEDIUM',
        High: 'HIGH',
        Critical: 'CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


