/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTaskRequest { 
    title?: string;
    description?: string;
    status?: UpdateTaskRequest.StatusEnum;
    priority?: UpdateTaskRequest.PriorityEnum;
    assigneeId?: string;
    dueDate?: string;
}
export namespace UpdateTaskRequest {
    export const StatusEnum = {
        Todo: 'TODO',
        InProgress: 'IN_PROGRESS',
        Done: 'DONE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PriorityEnum = {
        Low: 'LOW',
        Medium: 'MEDIUM',
        High: 'HIGH',
        Critical: 'CRITICAL'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


