/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProjectRequest { 
    name?: string;
    description?: string;
    status?: UpdateProjectRequest.StatusEnum;
}
export namespace UpdateProjectRequest {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Archived: 'ARCHIVED',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


