/**
 * TeamFlow API
 *
 * Contact: dev@teamflow.internal
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: string;
    username?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    role?: UserDto.RoleEnum;
    enabled?: boolean;
    createdAt?: string;
}
export namespace UserDto {
    export const RoleEnum = {
        User: 'USER',
        Admin: 'ADMIN'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


